var app = new Vue({
    el:'#app',
    data:{
        itemList:[
          {
            id:'1',
            itemName:'6吋堅果布朗尼',
            imgUrl:'images/buranni01.jpg',
            price:'450',
            count:'1'
          },
          {
            id:'2',
            itemName:'海鹽咖啡蛋糕',
            imgUrl:'images/Brown_cake02.jpg',
            price:'160',
            count:'1'
          },
          {
            id:'3',
            itemName:'紅絲絨蛋糕',
            imgUrl:'images/reaCake03.jpg',
            price:'160',
            count:'1'
          },
          {
            id:'4',
            itemName:'冷凍宅配特選聖代',
            imgUrl:'images/ice04.jpg',
            price:'55',
            count:'1'
          },
          {
            id:'4',
            itemName:'大理石馬卡龍',
            imgUrl:'images/makalon05.jpg',
            price:'60',
            count:'1'
          },
    ]
    },
    methods:{
        handlePlus: function(item){
            item.count++;
        },
        handleSub: function(item){
            if(item.count>1){
            item.count--;                
            }
        },
        handledelete: function(index){
            console.log(this);
            this.itemList.splice(index,1);
        }
    },
    computed:{

    }
})